multiplication implimented

diff --git a/project1/matrix b/project1/matrix
--- a/project1/matrix
+++ b/project1/matrix
@@ -4,7 +4,7 @@
 dims(){	
 	# DESCRIPTION
 	#	takes a filename as argument and prints its matrix dimensions
-	cols=$( wc -w < <( head <$1 -n 1 ) )
+	cols=$( head <$1 -n 1 |  wc -w  )
 	rows=$( wc -l <$1 )
 	echo "$rows $cols"
 }
@@ -15,7 +15,7 @@ transpose(){
 	#	takes a filename as argument and transposes its matrix elements
 
 	#number of existing rows = number of new columns
-	cols=$( wc -w < <( head <$1 -n 1 ) )
+	cols=$( head <$1 -n 1 |  wc -w  )
 	rows=$( wc -l <$1 )
 	
 	#iterate i through cols
@@ -42,8 +42,8 @@ add() {
 	#	adds two matrices
 
 	#check if addition is valid
-	m1cols=$( wc -w < <( head <$1 -n 1 ) )
-	m2cols=$( wc -w < <( head <$2 -n 1 ) )
+	m1cols=$( head <$1 -n 1 |  wc -w  )
+	m2cols=$( head <$2 -n 1 |  wc -w  )
 	m1rows=$( wc -l <$1 )
 	m2rows=$( wc -l <$2 )
 
@@ -77,7 +77,42 @@ mean(){
 }
 
 multiply() {
-echo "multiply"
+
+	#check if multiplication is valid
+	m1cols=$( head <$1 -n 1 |  wc -w  )
+	m2cols=$( head <$2 -n 1 |  wc -w  )
+	m1rows=$( wc -l <$1 )
+	m2rows=$( wc -l <$2 )
+
+	#cols in m1 must equal rows in m2
+	if [ $m1cols != $m2rows ]; then
+		echo "matrices cannot be multiplied" >&2
+		exit 4
+	fi
+
+	#final matrix has rows=m1rows and cols=m2cols
+	#element ij is the dot product of  m1's ith row and m2's jth column
+
+	# based off pseudocode from https://en.wikipedia.org/wiki/Matrix_multiplication_algorithm
+	while read -a m1line
+	do
+		for j in $(seq 0 $(expr $m2cols - 1 ) )
+		do
+			sum=0
+			i=0
+			while read -a m2line
+			do
+#				a=${m1line[$i]}
+#				b=${m2line[$j]}
+#				echo "m1[$i]=$a, m2[$j]=$b"
+				sum=$(expr $sum + ${m1line[$i]} \* ${m2line[$j]}  )
+				i=$(expr $i + 1 )
+			done <$2
+			echo -n -e "$sum"
+			[[ $j -lt $(expr $m1cols - 1 ) ]] && echo -e -n "\t"
+		done
+		echo ""
+	done <$1
 }
 
 
